# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Manage Audiences

# Attribute name
nameFrom: name

# Model Class name
modelClass: Pensoft\Results\Models\Category

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
